### ISSUE TITLE
Banner voor de github repositories.

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Art#12]
Er zou een rechthoekige balk van het logo moeten gemaakt worden. Dit is nodig zodat we ook het logo in de readme bestanden op github kunnen implementeren. 

**Afmetingen**
- breedte: 971px;
- hoogte: 297px;

**Idee:**

Om het actuele logo links of in het midden te zetten en gewoon die balk te bekomen door de afmetingen te vullen met de achtergrond kleur.

**Varia:**

Bij enige vragen tijdens het maken van de banner. Zou hebben dat je me contacteerd. Om misverstanden te voorkomen.

**Comment by alfamongrel** [comment]
ok word gemaakt

**Comment by Tjoosten** [comment]
**NOTE:** @tjoosten Follow up

**Comment by alfamongrel** [comment]
1ste ontwerp klaar indien ok ticket sluiten !
