### ISSUE TITLE
Front en background image voor de zorgsector petitie.

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Art#2]
Nu de barebone petitie is er bijna. Maar voor de zorgsector petitie hebben we nog 2 images nodig. 

- Background image (100% x 100%)
- Frontpage image (400px x 100%)

100% = schaalbaarheid aan de grootte van de browser.100% neemt de volledige grootte van de hoogte of breedte

**NOTE** Oliver moet dit nog bespreken met Tom.

**Comment by ghost** [comment]
![barner6](https://cloud.githubusercontent.com/assets/11593535/20641632/4a33eb8a-b3fc-11e6-8cb0-7a1e4fc589d3.jpg)

**Comment by ghost** [comment]
![leather_texture356](https://cloud.githubusercontent.com/assets/11593535/20641794/0805f3ee-b400-11e6-992e-d8d19ffb9a14.jpg)


Dit is bleeh de andere image dat ge nodig hebt. #TrektUwPlanErmee #LOL

**Comment by Tjoosten** [comment]
push then plz to the repo
