### ISSUE TITLE
Front end background image voor begrotingstekort petitie. 

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Art#6]
Nu de barebone petitie is er bijna. Maar voor de zorgsector petitie hebben we nog 2 images nodig.

Background image (100% x 100%)
Frontpage image (400px x 100%)
100% = schaalbaarheid aan de grootte van de browser.100% neemt de volledige grootte van de hoogte of breedte

NOTE Oliver moet dit nog bespreken met Tom.

**Comment by ghost** [comment]
![barner7](https://cloud.githubusercontent.com/assets/11593535/20641635/705e9486-b3fc-11e6-8a95-3735d8ac5524.jpg)

**Comment by ghost** [comment]
![a lot of money wallpaper 02 2560x1440](https://cloud.githubusercontent.com/assets/11593535/20641788/d03b3352-b3ff-11e6-8041-301afb784c8c.jpg)


Da's de bleeh andere image dat je nodig hebt.

**Comment by Tjoosten** [comment]
Push them plz to the repo
