### ISSUE TITLE
Logo. 

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Art#9]
@ubextreme can u design a logo. For the github organization? And push it to github.

**Comment by Tjoosten** [comment]
@ubextreme status update?

**Comment by ghost** [comment]
@Tjoosten Vandaag vraag ik het aan Frederik.. Dan zullen we da veel rapper hebben.

**Comment by Tjoosten** [comment]
@ubextreme let's hope. Can u also get the `.psd` and stuff. So i can close this issue.

**Comment by ghost** [comment]
@Tjoosten Normally i'll get the .psd also if i ask for it.

**Comment by Tjoosten** [comment]
@ubextreme new status update plz.

**Comment by ghost** [comment]
Logo is in **DEV.** in a few days max. it will be here finally.
